export const ROOT_URL = `${import.meta.env.VITE_API_URL}`;
export const ROOT_URL_LOGIN = `${import.meta.env.VITE_API_URL_LOGIN}`;
export const ROOT_URL_IMPORT = `${import.meta.env.VITE_API_IMPORT}`;

export const WS_CODE = {
  DETAIL_USER: "detailUser",
  LIST_ORDER_ESIM: "listOrdercrm",
  DETAIL_ORDER_ESIM: "detailOrderCrm",
  EXPORT_ORDER_ESIM: "export-order",
  EXPORT_ORDER_ESIM_SOLD: "export-esim",
  EXPORT_ORDER_ESIM_ERROR: "export-order-error",
  PREVIEW_ORDER: "preview-import-orders-vja",
  IMPORT_ORDER: "import-orders-vja",
  LIST_ORDER_ESIM_ERROR: "list-order-error",
  DETAIL_ORDER_ESIM_ERROR: "detail-order-error",
  LIST_CUSTOMER: "listCustomer",
  DETAIL_CUSTOMER: "detailCustomer",
  LIST_ACCOUNT: "listUser",
  DETAIL_ACCOUNT: "detailUser",
  LIST_ROLE: "getAllRole",
  UPDATE_ACCOUNT: "updateUser",
  UPDATE_PASSWORD: "updatePassword",
  CREATE_ACCOUNT: "addUser",
  LIST_CONTACT: "listContact",
  DETAIL_CONTACT: "detailContact",
  UPDATE_CONTACT: "updateContact",
  NEWS: "list-news",
  APPCODE: "list-appCode",
  CREATENEWS: "create-news",
  UPDATENEWS: "update-news",
  DETAILNEWS: "detail-news-crm",
  DEVICES: "crm-devices",
  DELETENEWS: "delete-news",
  UPLOADIMAGE: "uploadImage",
  LIST_PACKAGE: "listPackageCrm",
  DETAIL_PACKAGE: "detailPackageCrm",
  SYNC_PACKAGE: "sync-package",
  EXPORT_PACKAGE: "exportPackage",
  IMPORT_PACKAGE: "importPackage",
  UPDATE_PACKAGE: "updatePackageCrm",
  List_Exchange_Rate: "list-exchange-rate",
  DETAIL_EXCHANGE_RATE: "detail-exchange-rate",
  CREATE_EXCHANGE_RATE: "create-exchange-rate",
  GPAY_LOG: "list-gpay-log",
  LIST_AIRALO_LOG: "list-airalo-log",
  DETAIL_AIRALO_LOG: "detail-airalo-log",
  SYNCHRONIZED: "sync-compatible-device",
  LIST_ESIM_SOLD: "active",
  DETAIL_ESIM_SOLD: "detail",
  RETRY_ORDER_ESIM_ERROR: "retry-orders",
};

export const apiUrl = {
  LOGIN: "login",
  LISTCATEGORY: "category",
  CATEGORYID: "categoryId",
  PRODUCT: "product",
  PRODUCTBYID: "productId",
  ADDTRIBUTE: "createaddtribute",
  GETSADDTRIBUTE: "getsaddtribute",
};
